// react-front/src/app/home/components/home.jsx
import * as React from 'react';
import './home.css';
import Header from '../../components/navigate/header/header';
function Home() {
  return (
        <div id="mainBody">
        <link rel="stylesheet" href="home.css" />
        <div class="slogan">LA SALUD ORGANIZADA ES LA SALUD MEJORADA</div>
        <div class="grid-layout">
          <div appHasRole="general_patients">
            <button class="calendar" onclick="window.location.href='/home/calendar';">
              <img class="calendario" src="assets/calendario.png" alt="error de carga" />
            </button>
            <p>Calendario</p>
          </div>
          <div appHasRole="general_citas">
            <button class="citas" onclick="window.location.href='/home/citas';">
              <img class="citas" src="assets/hab.png" alt="error de carga" />
            </button>
            <p>Citas</p>
          </div>
        </div></div>

    
  );
}

export default Home;

// angular-front/src/app/home/home.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from "../navigate/header/header.component";

@Component({
    selector: 'app-home',
    standalone: true,
    templateUrl: './home.component.html',
    styleUrl: './home.component.css',
    imports: [HeaderComponent]
  })

export class HomeComponent {
  title = 'MedicaPlus';
}
<!DOCTYPE html>
<html>
<head>
    <title>Home</title>
</head>
<body>

<div class="slogan">La salud organizada es salud mejorada</div>

    <div class="grid-layout">
        <img class="left-up" src="assets/up_left.png" alt="error de carga"/>
        <img class="right-up" src="assets/up_right.png" alt="error de carga"/>
        <img class="left-mid" src="assets/panoramic_yes.png" alt="error de carga"/>
        <img class="right-mid" src="assets/hospi4.jpg" alt="error de carga"/>
        <img class="down" src="assets/mid_left.png" alt="error de carga"/>
    </div>
</body>
</html>
