// react-front/src/app/home/components/home.jsx
import * as React from 'react';
import './home.css';
import Header from '../../components/navigate/header/header';
function Home() {
  return (
        <div id="mainBody">
        <link rel="stylesheet" href="home.css" />
        <div class="slogan">LA SALUD ORGANIZADA ES LA SALUD MEJORADA</div>
        <div class="grid-layout">
          <div appHasRole="general_patients">
            <button class="calendar" onclick="window.location.href='/home/calendar';">
              <img class="calendario" src="assets/calendario.png" alt="error de carga" />
            </button>
            <p>Calendario</p>
          </div>
          <div appHasRole="general_citas">
            <button class="citas" onclick="window.location.href='/home/citas';">
              <img class="citas" src="assets/hab.png" alt="error de carga" />
            </button>
            <p>Citas</p>
          </div>
        </div></div>

    
  );
}

export default Home;

// angular-front/src/app/pages/home/components/home.component.ts
import { Component } from '@angular/core';
import { HeaderComponent } from "../../../components/navigate/header/header.component";

@Component({
    selector: 'app-home',
    standalone: true,
    templateUrl: './home.component.html',
    styleUrl: './home.component.css',
    imports: [HeaderComponent]
  })

export class HomeComponent {
  title = 'MedicaPlus';
}
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
  </head>
  <body>
    <div class="slogan">{{'HOME_SLOGAN' | translate}}</div>
    <div class="grid-layout">
      <div appHasRole="general_patients">
        <button class="patient" onclick="window.location.href='/home/patient';">
          <img class="people" src="assets/people.png" alt="error de carga" />
        </button>
        <p>{{'PATIENTS' | translate }}</p>
      </div>
      <div appHasRole="general_rooms">
        <button class="room" onclick="window.location.href='/home/room';">
          <img class="room" src="assets/hab.png" alt="error de carga" />
        </button>
        <p>{{'ROOMS' | translate}}</p>
      </div>
      <div appHasRole="general_workers">
        <button class="worker" onclick="window.location.href='/home/worker';">
          <img class="worker"  src="assets/stethoscope-svgrepo-com.svg" alt="error de carga">
        </button>
        <p>{{'WORKERS' | translate}}</p>
      </div>
    </div>
  </body>
</html>
